config/routes.rb
Rails.application.routes.draw do

  root to:'home#index', as: "root"
  require 'sidekiq/web'
  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :company_users, controllers: { sessions: 'client/sessions' }
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: "users/passwords"}

  get "auth/facebook/callback", to: "users/facebook#facebook", as: :get_user_from_token  

  # CURRENT USER
  get "users/:id", to: "users/user#show", as: :show_user
  get "me", to: "users/user#me", as: :show_me
  get "user/favorites", to: "users/user#get_favorites", as: :get_favorites
  get "user/applications", to: "users/user#get_applications", as: :get_applications
  get "user/removed", to: "users/user#get_removed", as: :get_removed
  get "user/counter-jobs-user", to: "users/user#counter_jobs_user", as: :counter_jobs_user
  get "user/applications/:job_id", to: "users/user#get_job_application", as: :get_job_application
  get "user/answers/:job_id", to: "users/user#get_job_answers", as: :get_job_answers
  post "user/cv-upload", to: "users/user#upload_resume", as: :upload_resume
  post "/job/remove", to: "users/user#job_remove", as: :job_remove
  post "/job/favorite", to: "users/user#job_favorite", as: :job_favorite

  # USERS
  get "/users/:id/resume", to: "users/user#download_resume", as: :resume_user
  post "/users/new-user-data", to: "users/user#new_user_data", as: :new_user_data
  post "/users/user-data-academic", to: "users/user#user_data_academic", as: :user_data_academic
  post "/users/user-career-status", to: "users/user#user_career_status", as: :user_career_status
  post "/users/user-ability", to: "users/user#user_ability", as: :user_ability
  post "/users/user-salary", to: "users/user#user_salary", as: :user_salary
  post "/users/user-assistantships", to: "users/user#user_assistantships", as: :user_assistantships
  post "/questions", to: "users/user#set_user_answers", as: :set_answers
  post "/users/user-extra-activities", to: "users/user#user_extra_activities", as: :user_extra_activities
  get "download/resume" => "client/process#download_resume", as: :download_resume

  # SEED FORM DATA
  get "/countries", to: "data#get_countries", as: :get_countries
  get "/careers", to: "data#get_careers", as: :get_careers
  get "/careers/:country_id", to: "data#get_careers_by_country", as: :get_careers_by_country
  get "/universities", to: "data#get_universities", as: :get_universities
  get "/universities/:country_id", to: "data#get_universities_by_country", as: :get_universities_by_country
  get "/questions", to: "data#get_questions", as: :get_questions

  # JOBS
  get "jobs", to: "users/jobs#index", as: :jobs
  get "jobs/:id", to: "users/jobs#show", as: :job
  get "job/data-for-filters", to: "users/jobs#data_for_filters"
  post "/job/apply", to: "users/jobs#job_apply", as: :job_apply
  delete "job/apply/:job_id", to: "users/jobs#job_apply_undo", as: :job_apply_undo
  get "jobs/:id/questions", to: "users/jobs#get_job_questions", as: :get_job_questions
  post "job/answer-job-questions", to: "users/jobs#answers_job_questions", as: :answers_job_questions
  get "job/filter", to: "users/jobs#filter_jobs"
  post "job/get-filtered-jobs", to: "users/jobs#get_filtered_jobs"
  post "job/button", to: "users/jobs#button_click_tracking"
  post "job/share", to: "users/jobs#share_click_tracking"

  ##  CLIENT

  get "empresas", to: "client/company#index", as: :client_index
  get "ingresar", to: "client/company#login", as: :client_login
  get 'empresas', to: "client/company#index", as: :root_companies
  get "productos" => "client/company#products", as: :home_products
  get "clientes" => "client/company#clients", as: :home_clients
  get "planes" => "client/company#plans", as: :home_plans
  get "contacto" => "client/company#contact", as: :home_contact
  get "publicar" => "client/company#publish", as: :home_publish
  get "ingresar" => "client/company#login", as: :home_login
  get "employer-branding" => "client/company#employer_branding", as: :employer_branding
  get "select-company", to: 'client/company#select_company', as: :select_company
  post "set-company", to: 'client/company#set_company_for_kam', as: :set_company_for_kam
  post "post_requests", to: "client/company#post_requests", as: :post_requests
  resources :post_requests, only: [:new, :create]

  # Contact form
  #get 'contact' => 'client/company#new', as: 'contact'
  post 'contact' => 'client/company#create', as: 'contact'
  ################################################################
  namespace :client do
    get "process", to: "process#index", as: :process_index
    get "process/:job_id", to: "process#show", as: :process_show
    get "process/:job_id/getexcel", to: "process#getexcel", as: :getexcel
    post "process/:job_id/getexcel", to: "process#getexcel", as: :getexcel_selected
    get "process/:job_id/getresumes", to: "process#get_job_resumes", as: :get_job_resumes
    post "process/:job_id/getresumes", to: "process#get_job_resumes", as: :get_job_resumes_selected
    post "process/:job_id/republish", to: "process#republish", as: :republish_job

    get "get-application-answers/:id", to: "process#get_application_answers", as: :get_application_answers
    get "get-application-comments/:id", to: "process#get_application_comments", as: :get_application_comments
    get "job/:job_id", to: "process#get_job_details"
    get "users/:user_id/resume", to: "process#get_user_resume", as: :get_user_resume
    get "users/:user_id/display-resume", to: "process#display_resume", as: :display_resume
    get "users/:user_id/check_resume", to: "process#check_resume", as: :check_resume
    get "job/:job_id/applicants", to: "process#get_applicants_for_job"
    post "process/request_candidates", to: "process#request_candidates", as: :request_candidates
    post "process/set_job_state", to: "process#set_job_state", as: :set_job_state
    post "users/like", to: "process#likes_buttons", as: :likes_buttons


    ################################################################
    get "users/:user_id/profile", to: "process#get_profile_partial", as: :get_profile_partial
    get "users/:user_id/process", to: "process#get_process_partial", as: :get_process_partial
    get "users/:user_id/answers", to: "process#get_answers_partial", as: :get_answers_partial
    get "users/:user_id/comments", to: "process#get_comments_partial", as: :get_comments_partial
    post "users/:user_id/new-comment", to: "process#new_application_comment", as: :new_application_comment
    post "users/delete_comment/:comment_id", to: "process#delete_application_comment", as: :delete_application_comment
    post "users/add_applicant", to: "process#add_applicant", as: :add_applicant
    post "users/edit_comment", to: "process#edit_application_comment", as: :edit_application_comment
    ################################################################
    get "publish/new", to: "publish#process_step_1", as: :new_process
    post "publish/create_process", to: "publish#create_process", as: :create_process

    get "publish/:job_id/step1", to: "publish#edit_step_1", as: :edit_step_1
    patch "publish/step1_values", to: "publish#process_step_1_update", as: :process_step_1_update

    get "publish/:job_id/step2", to: "publish#process_step_2", as: :process_step_2
    patch "publish/step2_values", to: "publish#process_step_2_update", as: :process_step_2_update

    get "publish/:job_id/step3", to: "publish#process_step_3", as: :process_step_3
    patch "publish/step3_values", to: "publish#process_step_3_update", as: :process_step_3_update

    get "publish/:job_id/step4", to: "publish#process_step_4", as: :process_step_4
    post "publish/:job_id/add-question", to: "publish#add_question", as: :add_question
    post "publish/delete-question", to: "publish#delete_question", as: :delete_question
    post "publish/update-question", to: "publish#update_question", as: :update_question
    patch "publish/step4_values", to: "publish#process_step_4_update", as: :process_step_4_update

    get "publish/add_new_question", to: "publish#add_new_question", as: :add_new_question

    get "publish/:job_id/step5", to: "publish#process_step_5", as: :process_step_5
    patch "publish/step5_values", to: "publish#process_step_5_update", as: :process_step_5_update
    get "publish/:job_id/step6", to: "publish#process_step_6", as: :process_step_6
    ################################################################
    get "configuration", to: "configuration#index", as: :configuration
    get "insigths", to: "insigths#index", as: :insigths
    get "interviews", to: "interviews#index", as: :interviews
    ################################################################
    get "search", to: "search#index", as: :search
    post "/data-for-countries", to: "search#data_for_countries", as: :data_for_countries

  end

end

app/controllers/client/company_controller.rb
class Client::CompanyController < ApplicationController

  def index
    render layout: "companies"
  end

  def login
    redirect_to client_process_index_path if current_company_user.present?
  end

  def select_company
      @companies = Company.all.order(name: :asc)
  end

  def set_company_for_kam
    company_id = params[:current_company_id]
    current_company_user.update_attribute(:current_company_id, company_id)
    redirect_to client_process_index_path
  end

  def products
    @page_title = "Productos"
    render layout: "companies"
  end

  def plans
    @page_title = "Nuestros planes"
    render layout: "companies"
  end

  def publish
    @page_title = "Publica un trabajo"
    render layout: "companies"
  end

  def clients
    @page_title = "Clientes"
    render layout: "companies"
  end

  def contact
    @page_title = "Contacto"
    @reviews = Review.company.sample(2)
    render layout: "companies"
  end

  def post_requests
    params.permit!
    @post_request = PostRequest.new(params[:post_request])
    if @post_request.save
      flash[:notice] = "Successfully created post_request."
      Notifier.new_post_request(@post_request).deliver_now
      render js: "publish_ok();"
    else
      render js: "alert('Favor intentar nuevamente.');"
    end

  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      Notifier.new_message(@message).deliver_now
      render js: 'contact_ok();'
    else
      render js: 'contact_error();'
    end
  end

end

app/controllers/client/configuration_controller.rb
class Client::ConfigurationController < ApplicationController

  def index    
  end
  
end

app/controllers/client/insigths_controller.rb
class Client::InsigthsController < ApplicationController

  def index
    @jobs = Job.select("id").get_all_jobs_from_company current_company_user, "todos", "created_at"
    @accounts = Account.select("id").search_account_from_process(current_company_user)
  end
  
end

app/controllers/client/interviews_controller.rb
class Client::InterviewsController < ApplicationController

  def index    
  end

end

app/controllers/client/publish_controller.rb
class Client::PublishController < ApplicationController

  before_action :set_dependences, only: [:edit_step_1, :process_step_1]
  before_action :set_job, only: [:edit_step_1, :update, :destroy, :process_step_2, :process_step_3, :process_step_4]
  before_action :set_job, only: [:process_step_1_update, :process_step_2_update, :process_step_3_update, :process_step_4_update, :process_step_5_update]

  def process_step_1
    @url = client_create_process_path
    @job = Job.new
  end

  def edit_step_1
    @url = client_process_step_1_update_path
    @job = Job.find(params[:job_id])
    render template: "client/publish/process_step_1"
  end

  def create_process
    @job = Job.new(step_1_params)
    @job.state = 1
    @job.posted_by_id = current_company_user.id
    @job.published = false
    return render js: "window_location('#{client_process_step_2_path(@job.id)}')", status: 200 if @job.save
    render js: 'swal("Debes completar todos los campos.");'
  end

  def process_step_2
    @job = Job.find(params[:job_id])
    @universities = University.where(country_id: @job.countries).order(name: :asc)
    @careers = Career.where(country: @job.countries).order(name: :asc)
    @job_statuscareer = @job.job_statuscareer
  end

  def process_step_3
    @job = Job.find(params[:job_id])
    @values = [0,1,2,3,4,5]
  end

  def process_step_4
    @job = Job.find(params[:job_id])
    @questions = @job.questions.order(id: :asc)
  end

  def add_question
    job_id = params[:question][:job_id]
    content = params[:question][:content]
    question = Question.new(job_id: job_id, content: content)
    render js: "location.reload();", status: 200 if question.save
  end

  def delete_question
    question_id = params[:question_id]
    question = Question.find(question_id)
    render js: "location.reload();", status: 200 if question.destroy
  end

  def update_question
    question_id = params[:question_id]
    content = params[:content]
    question = Question.find(question_id)
    question.content = content
    question.save if question.job.company_id == current_company_user.company_id
    render js: "location.reload();", status: 200
  end

  def process_step_5
    @job = Job.find(params[:job_id])
  end

  def process_step_6
    @job = Job.find(params[:job_id])
  end

  def process_step_1_update
    is_ok = @job.update(step_1_params)
    @job.update(state: 1) if @job.state == nil
    return render js: "window_location('#{client_process_step_2_path(@job.id)}')", status: 200 if is_ok
    render js: 'swal("Debes completar todos los campos.");'
  end

  def process_step_2_update
    return render js: 'swal("Debes completar todos los campos.");' if step_2_params[:english_level].blank? || step_2_params[:excel_level].blank?
    @job.update(step_2_params)

    if params[:job].present?
      if params[:job][:job_statuscareer_attributes].present? && 
        (params[:job][:job_statuscareer_attributes][:student] == "0" or !params[:job][:job_statuscareer_attributes][:student].present?)
        @job.update(age_study: nil) 
      end
      if params[:job][:job_statuscareer_attributes].present? && 
        (params[:job][:job_statuscareer_attributes][:graduate] == "0" and params[:job][:job_statuscareer_attributes][:qualified] == "0")
        @job.update(years_experience: nil)
      end
    end 
    # if !params[:job][:job_statuscareer_attributes][:qualified].present?
    #   @job.update(years_experience: nil)
    # end
    render js: "window_location('#{client_process_step_3_path(@job.id)}')", status: 200
  end

  def process_step_3_update
    return render js: 'swal("Debes completar todos los campos.");', status: 500 if params[:job].blank? || ( params[:job].present? && params[:job].length < 5 )
    is_ok = @job.update(step_3_params)
    return render js: "window_location('#{client_process_step_4_path(@job.id)}')", status: 200 if is_ok
    render js: 'swal("Debes completar todos los campos.");', status: 500
  end

  def process_step_4_update
    @job.update(step_4_params) if params[:job].present?
    render js: "window_location('#{client_process_step_5_path(@job.id)}')", status: 200
  end

  def process_step_5_update
    @job.update(state: 2)
    Job.calcule_matchs(12, @job.id, nil)
    render js: "window_location('#{client_process_step_6_path(@job.id)}')", status: 200
  end

  def add_new_question
    @question_key =  SecureRandom.random_number(36**6).to_s(36).rjust(6, "0") # random 6 chars
    @count = params[:count]
    html = render_to_string "client/publish/_new_question", :layout => false
    render text: html, status: 200
  end

  private
  def set_dependences
    @countries = Country.all
  end

  def set_job
    @job = Job.find(params[:job_id])
  end

  def step_1_params
    params.require(:job).permit(:title, :description, :location, :show_salary, :looking_for, :company_id, :availability, :vacancies, :maximum_salary_offered, country_ids: [])
  end

  def step_2_params
    params.require(:job).permit(:looking_for, :years_experience, :english_level, :excel_level, :show_salary, :age_study, university_ids: [],
     career_ids: [], job_statuscareer_attributes: [:student, :graduate, :qualified, :id])
  end

  def step_3_params
    params.require(:job).permit(:filter_califications, :filter_assistantship, :filter_extra_activities, :filter_student_activities, :filter_student_project)
  end

  def step_4_params
    params.require(:job).permit!
  end

end

app/controllers/client/search_controller.rb
class Client::SearchController < ApplicationController

  require 'action_view/helpers/javascript_helper'
  include ActionView::Helpers::JavaScriptHelper

  def index
    @accounts = Account.search_accounts(current_company_user, params)
    @countries = Country.all
    @universities = University.for_countries(params[:countries_ids])
    @careers = Career.for_countries(params[:countries_ids])
  end

  def data_for_countries
    countries_ids = params[:countries_ids]
    @universities = University.for_countries(countries_ids)
    @careers = Career.for_countries(countries_ids)
    html_text = escape_javascript render_to_string "client/search/_universities_careers", :layout => false
    return render js: "$('#universities_careers').html('#{html_text}');" , status: 200
  end

end

app/controllers/client/sessions_controller.rb
class Client::SessionsController < Devise::SessionsController

  def create
    self.resource = warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#failure_company")
    sign_in(resource_name, resource)  
    render js: "window.location='#{client_process_index_url}';"
  end

  def failure_company
    render js: "$('.login-box').css('display', 'block')", status: 406
  end

end

app/views/client/publish/_new_question.html.erb
<div class="question-<%= @question_key %>">
  <div class="input hidden job_questions_id">
    <input class="hidden" type="hidden" name="job[questions_attributes][<%= @count %>][id]" id="job_questions_attributes_<%= @count %>_id">
  </div>
  <div class="input string optional job_questions_content">
    <input class="string optional" type="text" value="" 
    name="job[questions_attributes][<%= @count %>][content]" id="job_questions_attributes_<%= @count %>_content"
    placeholder="Déjala en blanco, si deseas que no se guarde"
    >
  </div>
  <input value="0" class="destroy-11564" type="hidden" name="job[questions_attributes][<%= @count %>][_destroy]" id="job_questions_attributes_<%= @count %>__destroy">
  <a class="remove-question" data-id="<%= @question_key %>" href="#">X</a>
</div>

app/views/client/publish/process_step_1.html.erb
<%= simple_form_for @job, :url => step1_route(@job), remote: true do |f| %>
<div class="row process_publish" style="padding-top: 7%;">
  <div class="col-sm-12">
    <div class="form-group">
      <% if @job.id.present? %>
      <input type="hidden" value="<%= @job.id %>" name="job_id"></input>
      <% end %>
      <input type="hidden" value="<%= current_company_user.company_id %>" name="job[company_id]">
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-5">
          <%= f.input :looking_for,
                  label: 'TIPO DE OFERTA',
                  collection: I18n.t(:looking_for).invert,
                  as: :radio_buttons
          %>
        </div>
        <div class="col-md-5">
          <%= f.input :location,  as: :string,  label: "UBICACIÓN", label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-5">
          <%= f.input :show_salary,  as: :boolean,  label: "Mantener renta oculta?", label_html: { class: 'form-label' } %>
          <%= f.label :maximum_salary_offered, "RENTA" , class:"renta", required: true %>
          <%= f.input :maximum_salary_offered, label: false ,as: :string,  label_html: { class: 'form-label' }, input_html: { class: 'form-control' }, required: true %>
        </div>
        <div class="col-md-5">
          <%= f.association :countries, label: "PAÍSES FOCO", collection: @countries, input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-5">
          <%= f.input :vacancies,  as: :string,  label: "VACANTES", label_html: { class: 'form-label' }, input_html: { class: 'form-control' }, required: true %>
        </div>
        <div class="col-md-5">
          <%= f.input :availability, label: "DISPONIBILIDAD", collection: Job::AVAILABILITY.invert , as: :radio_buttons %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
          <%= f.input :title,  as: :string,  label: "NOMBRE DEL PROCESO", label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
          <%= f.input :description,  as: :text,  label: "AGREGA UNA DESCRIPCIÓN", label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
        </div>
      </div>
      <div class="row" align="center">
        <div class="col-md-5"></div>
        <div class="col-md-2 text-center" style="padding-bottom: 2%;">
          <%= f.button :submit, "Siguiente" , class: "form-control" %>
        </div>

      </div>
    </div>
  </div>
</div>
<% end %>

app/views/client/publish/process_step_2.html.erb
<div class="basics_filter">
  <h1>FILTROS BÁSICOS</h1>

  <%= simple_form_for @job, :url => client_process_step_2_update_path, remote: true do |f| %>
    <% if @job.id.present? %>
      <input type="hidden" value="<%= @job.id %>" name="job_id"/>
    <% end %>

    <% f.input :career_status,
               label: "TIPO DE POSTULANTE",
               collection: I18n.t(:career_status).invert,
               as: :radio_buttons
    %>

    <div class="row">
      <div class="col-md-6 job_career_status">
        <label class="optional">TIPO DE POSTULANTE</label>
        <% if @job.job_statuscareer.present? %>
          <%= f.simple_fields_for :job_statuscareer do |js| %>
            <% if @job.looking_for != 3 %>
              <span class="checkbox">
                <%= js.check_box :student %>
                <%= js.label :student, Job.career_status[0][0] %>
              </span>
            <% else %>
              <input name="job[job_statuscareer_attributes][student]" type="hidden" value="0">
            <% end %>
            <span class="checkbox">
              <%= js.check_box :graduate %>
              <%= js.label :graduate, Job.career_status[1][0] %>
            </span>
            <% if @job.looking_for == 3 %>
              <span class="checkbox">
                <%= js.check_box :qualified %>
                <%= js.label :qualified, Job.career_status[2][0] %>
              </span>
            <% else %>
                <input name="job[job_statuscareer_attributes][qualified]" type="hidden" value="0">
            <% end %>
          <% end %>
        <% else %>
          <%= f.simple_fields_for :career_status do |js| %>
            <% if @job.looking_for != 3 %>
              <span class="checkbox">
                <%= js.check_box :student %>
                <%= js.label :student, Job.career_status[0][0] %>
              </span>
            <% else %>
              <input name="job[career_status][student]" type="hidden" value="0">
            <% end %>
            <span class="checkbox">
              <%= js.check_box :graduate %>
              <%= js.label :graduate, Job.career_status[1][0] %>
            </span>
            <% if @job.looking_for == 3 %>
              <span class="checkbox">
                <%= js.check_box :qualified %>
                <%= js.label :qualified, Job.career_status[2][0] %>
              </span>
            <% else %>
              <input name="job[career_status][qualified]" type="hidden" value="0">
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 hidden">
      <%= f.input :age_study, label: "AÑO QUE CURSA", collection: [1,2,3,4,5,6], as: :radio_buttons%>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 hidden">
      <%= f.input :years_experience, label: "EXPERIENCIA", collection: I18n.t(:years_experience).invert, as: :radio_buttons %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= f.input :english_level, label: "NIVEL DE INGLÉS", collection: I18n.t(:english_level).invert, as: :radio_buttons %>
      </div>
      <div class="col-md-6">
        <%= f.input :excel_level, label: "NIVEL DE EXCEL", collection: I18n.t(:excel_level).invert, as: :radio_buttons, class:"form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= f.association :universities, label: "UNIVERSIDADES", collection: @universities, input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
      </div>
      <div class="col-md-6">
        <%= f.association :careers, label: "CARRERAS", collection: @careers, input_html: { class: 'form-control' }, label_html: { class: 'form-label' } %>
      </div>
    </div>
    <% f.input :show_salary,  as: :boolean,  label: "Elegir carreras similares?", label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>

    <div class="row" style="margin-top:5%;padding-bottom: 5%;">
      <div class="col-md-4"></div>
      <div class="col-md-2 text-right">
        <a class="btn btn-default form-control" href="<%= client_edit_step_1_path %>">Anterior</a>
      </div>
      <div class="col-md-2 text-left">
        <button type="submit" class="btn btn-default form-control">Siguiente</button>
      </div>
    </div>

  <% end %>
</div>

app/views/client/publish/process_step_4.html.erb
<div class="add_questions">

  <div class="row">
    <div class="col-md-12 text-center">
      <h1>AGREGA PREGUNTAS PARA EL POSTULANTE</h1>
    </div>
  </div>

  <div class="row">
    <form class="form-horizontal" action="<%= client_add_question_path(@job.id) %>" method="POST" data-remote="true">
      <input type="hidden" name="question[job_id]" value="<%= @job.id %>">
      <div class="form-group">
        <div class="col-md-1"></div>
        <div class="col-md-8" style="margin:0;padding:0">
          <input type="text" class="form-control" id="question-content" name="question[content]" placeholder="Escribe aquí tu pregunta">
        </div>
        <div class="col-md-2" style="margin:0;padding:0;">
          <button type="submit" class="btn btn-agregar form-control">Agregar</button>
        </div>
      </div>
    </form>
  </div>
  <div class="questions">
    <% @questions.each_with_index do |question, index| %>
      <div class="row">
        <div class="col-md-1"></div>
        <p class="col-md-8"><%= index + 1 %>.- <%= question.content %></p>
        <button class="btn col-md-1 update-question" data-question-id="<%= question.id %>" data-question-content="<%= question.content %>" >
          <i class="fa fa-pencil"></i>
          Editar
        </button>
        <button type="submit" class="btn col-md-1 delete-question" data-question-id="<%= question.id %>" data-question-content="<%= question.content %>">
          <i class="fa fa-trash-o"></i>
          Borrar
        </button>
      </div>
    <% end %>
  </div>
  <div class="row" style="margin-top:5%;">
    <div class="col-md-4"></div>
    <div class="col-md-2 text-right">
      <a class="btn btn-default form-control" href="<%= client_process_step_3_path %>">Anterior</a>
    </div>
    <div class="col-md-2 text-left">
      <a class="btn btn-default form-control" href="<%= client_process_step_5_path %>">Siguiente</a>
    </div>
  </div>
</div>

app/views/client/publish/process_step_6.html.erb
<div class="finish-publish">
  <div class="col-md-12 text-center">
    <div class="row">
      <span class="fa-stack fa-lg fa-5x">
        <i class="fa fa-square-o fa-stack-2x"></i>
        <i class="fa fa-check fa-stack-1x"></i>
      </span>
    </div>
    <div class="row title">
        <h1>Has publicado exitosamente!</h1>
    </div>
    <div class="row subtitle">
        <h4>Comparte para tener más éxito en tu búsqueda</h4>
    </div>
    <div class="row shares">
      <div class="col-md-2 col-md-offset-4 btn-fb btn" rel="nofollow"
         href="http://www.facebook.com/"
         onclick="popUp=window.open(
             'http://www.facebook.com/sharer.php?u=https://firstjob.me/jobs/<%= @job.slug %>',
             'popupwindow',
             'scrollbars=yes,width=800,height=400');
             popUp.focus();
             return false">
        <i class="fa fa-facebook" aria-hidden="true"></i>Comparte con Facebook
      </div>
      <div class="btn col-md-2 btn-linkedin" rel="nofollow"
           href="http://www.linkedin.com/"
           onclick="popUp=window.open(
               'http://www.linkedin.com/shareArticle?mini=true&url=https://firstjob.me/jobs/<%= @job.slug %>&title=<%= @job.title %>&source=https://firstjob.me',
               'popupwindow',
               'scrollbars=yes,width=800,height=400');
               popUp.focus();
               return false">
        <i class="fa fa-linkedin" aria-hidden="true"></i>Comparte con Linkedin
      </div>
    </div>
    <div class="row go-process">
      <a href="<%= client_process_index_path %>" class="btn col-md-4 col-md-offset-4">IR A PROCESOS</a>
    </div>

  </div>
</div>